AllCops:
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
    - bin/*
    - config/**/
    - node_modules/**/**.*

Rails:
  Enabled: true

Documentation:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

DotPosition:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - config/**/*.rb
    - test/**/*.rb

Metrics/LineLength:
  Max: 125
  Exclude:
    - config/**/*.rb

Style/RegexpLiteral:
  Enabled: false

Metrics/MethodLength:
  Max: 12

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb
